### ISSUE TITLE
Installation fails on RaspberryPi

### ISSUE THREAD

**Issue by HeinrichHartmann** [circonus-labs/circonus-one-step-install#9]
Running the copy paste command on a RPi (model-b, raspbian 7 (wheezy)) gives an error:

```
Started Circonus One step Install on Sun Nov  6 09:52:30 UTC 2016
Initializing cosi-install
Parsing command line parameters
Verifying COSI support for OS
        Attempt Debian(variant) detection
        Looking up Linux raspbian v7 unknown.

ERROR: API result - http result code: 409
message: Invalid OS architecture 'unknown', ref id: 5b2ba133-71cd-4d23-939f-3c878d4a43bf
```

```
pi@pi ~ $ uname -a
Linux pi 4.1.7+ #817 PREEMPT Sat Sep 19 15:25:36 BST 2015 armv6l GNU/Linux
pi@pi ~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
NAME="Raspbian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=raspbian
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by HeinrichHartmann** [comment]
Traceing this error back I find:
- This URL yielding a 409 `https://onestep.circonus.com/package?type=Linux&dist=raspbian&vers=7&arch=unknown`
- And `uname -p` => `unknown`

The CPU architecture of the PI can be determined by:
- `dpkg --print-architecture` => `armhf`
- `lscpu | grep Architecture` => `armv6l`
  Substituting both of which in the above URL yields the same result.

**Comment by maier** [comment]
We don't build packages for ARM at this time. So, even if the standard `uname -p` were to return a valid architecture (instead of 'unknown'), we still couldn't complete installation.
